### PR TITLE
Enhance performance

### PR DESCRIPTION
**Pull request by zhang-shengping**

### CODE REVIEW

**Comment by zongzw** [comment]
Peter, your change is aimed to reduce the RPC msg size? is my understanding correct?

If that, personal speaking, I think reducing RPC call times should be more helpful than reducing the size.. From Agent side, when reporting status, agent call RPC multiple (too many) times for already 'active' objects.

However, I believe you are deeper observing on this issue. 
Do you have the report comparable before and after your change, so that we can trace the coding improvement.

**Comment by zhang-shengping** [comment]
@zongzw In f5 driver side, I try to reduce MySQL calls, by targeting on some more specific objects that required to build a service.

**Comment by zhang-shengping** [comment]
```
TEST:
Mitaka f5lbaas:
    1. 55 listeners within the same loadbalancer. 
    2. add the 56th listener:
         f5-driver consumes time: 28.0387439728 seconds
         f5-agent consumes time: 44.0796728134 seconds
    3. delete the 56th listener:
         f5-driver consumes time: 28.2238118649 seconds
         f5-agent consumes time: 40.2288701534 seconds
    
    after enhance performance:

    1. 55 listeners within the same loadbalancer. 
    2. add the 56th listener:
         f5-driver consumes time: 1.45948505402 seconds
         f5-agent consumes time:  0.779107093811 seconds
    3. delete the 56th listener:
         f5-driver consumes time: 1.42936491966 seconds
         f5-agent consumes time:  0.36824798584 seconds
```

**Comment by zhang-shengping** [comment]
Fix problem between l7policy and pool, member and healthmonitor.

**Pull request closed without merging**
