### PR TITLE
Syntax error for Differentiated Service Environments documentation page

### LINKED ISSUE #259: Differentiated Service Environments documentation syntax issue
The page for Differentiated Service Environments (includes/topic_differentiated-services.rst) had an incorrect :ref: tag, so the link was not built correctly.

### PR DESCRIPTION
**Pull request by rsalsa**
Issues:
Fixes #259

Problem: Includes/topic_differentiated-services.rst had an incorrect :ref: tag, so the link was not built correctly back to the referenced page.

### CODE REVIEW

**Comment by jputrino** [comment]
Looks good! Thanks @rsalsa :)

**Comment by jputrino** [comment]
I just noticed that this PR is into master. Please close this one and open a new one into Liberty. It will be merged up from Liberty -> Mitaka -> Master.

Thanks!

**Comment by rsalsa** [comment]
Done. Base changed to Liberty. Thanks!

**Comment by jputrino** [comment]
@rsalsa - Something is off here, we need to touch base on this. Send you an email offline.

**Comment by richbrowne** [comment]
Hi Rick,  I can't see what changed here.

**Comment by jputrino** [comment]
@richbrowne - I'm actually closing this one out, @rsalsa is going to open a new one because his branch was based on master instead of liberty. He fixed a sphinx syntax error.

**Comment by richbrowne** [comment]
I see the change.  I can make the fix in my branch.

**Comment by richbrowne** [comment]
Ok, I will wait for Rick's updated pull request.

Thanks,

**Pull request closed without merging**
