### PR TITLE
Selective chowning of openstackdev specific files permits successful nightly teardown without affecting other project files.

### PR DESCRIPTION
**Pull request by zancas**
@pjbreaux 

Most of the relevant context for this PR is already documented in #711 .

For additional detail see the commit messages.

Tests:

http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/mitaka/job/za_test_11.6.1_undercloud_vxlan/22/consoleFull

### CODE REVIEW

**Comment by pjbreaux** [comment]
@zancas: is this the latest success for these changes? http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/mitaka/job/za_test_11.6.1_undercloud_vxlan/

**Comment by zancas** [comment]
Note because of the creative history of this PR, this critical change is not displayed in the PR commits:

https://github.com/F5Networks/f5-openstack-lbaasv2-driver/commit/b20d1cfa1dd827844675228c733502a272569354

**Comment by zancas** [comment]
Yes the jenkins log is for the test I just ran...

Hold off merge, I will kick one more post-rebase.

**Comment by zancas** [comment]
The rebase shouldn't have changed any code, but I'm feeling wary due to some of the changes being outside the PR proper...   testing now.

**Comment by zancas** [comment]
Anyone who has nothing better to do:

http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/mitaka/job/za_test_11.6.1_undercloud_vxlan/23/console

**Comment by zancas** [comment]
OK, that succeeded.   This is developer-test ready, as evidenced by this:

http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/mitaka/job/za_test_11.6.1_undercloud_vxlan/23/console

**Comment by pjbreaux** [comment]
The build succeeded, but there was a permissions denied error: search for `error: could not create`

**Comment by zancas** [comment]
and this:

http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/mitaka/job/za_test_11.6.1_undercloud_vxlan/

**Comment by zancas** [comment]
Hmm...  that's interesting...

**Comment by zancas** [comment]
Based on @pjbreaux 's review:

  * tox was installing the driver onto the test runner
  When the driver is NOT installed on the test runner:
   There are:  18 passes and 31 errors in the "tempest" suite
          http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/mitaka/job/za_test_11.6.1_undercloud_vxlan/26/console


   When the driver IS installed on the test runner:
     There are:  46 passes and 2 fails and 1 error

http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/mitaka/job/za_test_11.6.1_undercloud_vxlan/27/console

It would be ideal to understand why this is necessary and perhaps refactor to remove the boundary-violating dependancy:   #721


In the interim the driver is explicitly installed immediately before the run on the "tempest" tests.

**Comment by zancas** [comment]
I am conservatively testing this refactor now, DON'T MERGE YET!

Here's the run of the refactor (for the curious):

http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/mitaka/job/za_test_11.6.1_undercloud_vxlan/28/console

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by pjbreaux** [comment]
test this please

**Comment by pjbreaux** [comment]
@zancas: I'm ready to merge. All smoke tests pass, but I'd like to get some of these commits cleaned up or squashed.

**Comment by zancas** [comment]
If this had been merged yesterday these jenkins jobs would be Blue not Red:

http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/mitaka/


The reasons to leave development commits unsquashed is two-fold:

1.   It provides finer grained auditability.
2.   The actual test jenkins runs used to validate theses commits refer to commits in the development branch.   Squashing-or-rebasing destroys this information.   In order to preserve this data I have opted to add revert commits.

**Comment by pjbreaux** [comment]
@zancas: ah gotcha, then please use the commit template to describe those changes and why.

**Pull request merged**
