### PR TITLE
Stable/newton

### PR DESCRIPTION
**Pull request by pjbreaux**
@szakeri @zancas
#### What's this change do?
Merging mitaka forward into stable/newton

### CODE REVIEW

**Comment by pjbreaux** [comment]
retest this please

**Comment by pjbreaux** [comment]
retest this please

**Comment by pjbreaux** [comment]
retest this please

**Comment by pjbreaux** [comment]
retest this please

**Comment by jputrino** [comment]
FYI @jlongstaf @zancas @szakeri  -- this PR doesn't incorporate the updated docs test script, so you may see the docs test fail. That change is in liberty and needs to be merged forward.

**Comment by pjbreaux** [comment]
retest this please

**Comment by pjbreaux** [comment]
retest this please

**Comment by pjbreaux** [comment]
test this please

**Comment by pjbreaux** [comment]
test this please

**Comment by pjbreaux** [comment]
retest this please

**Comment by pjbreaux** [comment]
retest this please

**Comment by pjbreaux** [comment]
retest this please

**Comment by zancas** [comment]
test this please

**Comment by zancas** [comment]
test this please

**Pull request closed without merging**
