### PR TITLE
Mitaka

### PR DESCRIPTION
**Pull request by zancas**
@pjbreaux clean up unused "`Docker`" directory, and add appropriate variable.

### CODE REVIEW

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by pjbreaux** [comment]
test this please

**Comment by pjbreaux** [comment]
@zancas: the build on PR failed due to:

```
ERROR: Failed to clean the workspace
java.io.IOException: Unable to delete '/var/jenkins/workspace/smoke_test'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at hudson.Util.deleteContentsRecursive(Util.java:228)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:488)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.AccessDeniedException: /var/jenkins/workspace/smoke_test/systest/test_results/f5-openstack-lbaasv2-driver_mitaka-tempest_smoke_test/scenario_19f7843_20170721-194626/scenario_19f7843_20170721-194626-neutron_lbaas.tests.tempest.v2.scenario.test_session_persistence.testsessionpersistence.test_session_persistence-testresult.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at hudson.Util.tryOnceDeleteFile(Util.java:287)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:364)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:363)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:363)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:363)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:363)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.deleteContentsRecursive(Util.java:223)
	... 11 more
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Failed to delete workspace
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:491)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at ......remote call to docker-exe(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
	at sun.reflect.GeneratedMethodAccessor1198.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
	at com.sun.proxy.$Proxy105.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1070)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1110)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:83)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:73)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unable to delete '/var/jenkins/workspace/smoke_test'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
	at hudson.Util.deleteContentsRecursive(Util.java:228)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:488)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	... 4 more
Caused by: java.nio.file.AccessDeniedException: /var/jenkins/workspace/smoke_test/systest/test_results/f5-openstack-lbaasv2-driver_mitaka-tempest_smoke_test/scenario_19f7843_20170721-194626/scenario_19f7843_20170721-194626-neutron_lbaas.tests.tempest.v2.scenario.test_session_persistence.testsessionpersistence.test_session_persistence-testresult.json
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at hudson.Util.tryOnceDeleteFile(Util.java:287)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:364)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:363)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:363)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:363)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.tryOnceDeleteRecursive(Util.java:363)
	at hudson.Util.tryOnceDeleteContentsRecursive(Util.java:383)
	at hudson.Util.deleteContentsRecursive(Util.java:223)
	... 11 more
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] dir
Required context class hudson.FilePath is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
```

**Comment by zancas** [comment]
The permissions issue affecting the smoketest on PR results is not in the scope of this PR.

**Comment by zancas** [comment]
@ssorenso here's a link to the passing tests:

http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/mitaka/job/12.1.1-undercloud-vxlan/82/consoleFull

**Comment by pjbreaux** [comment]
@zancas: please squash, sir.

**Pull request merged**
