### PR TITLE
Fixes #717 - add redirect from RTD to clouddocs

### LINKED ISSUE #717: Add a redirect from Read the Docs to clouddocs.f5.com
#### OpenStack Release
Liberty

#### Description
Now that documentation publishes to clouddocs.f5.com, we need to redirect users from read the docs to the new product documentation on clouddocs. 

This is done via javascript embedded in the html body of each page by the sphinx `rst_prolog`.

### PR DESCRIPTION
**Pull request by jputrino**
@pjbreaux @szakeri 

#### What issues does this address?
Fixes #717 

#### What's this change do?
- Adds a redirect to clouddocs.f5.com for users that are trying to access the docs on read the docs.
- Fixes a sphinx rendering issue (lines 331 & 363) -- adding the `\` tells sphinx not to render the URL as a hyperlink.
- Adjusts the target for the link to the agent product docs -- we're pointing at agent/openstack_version instead of agent/agent_version. This is consistent with similar links in other product repos.

#### Where should the reviewer start?
View changes in-line below.

#### Any background context?
This change can be merged in either before or after the release is made, as you see fit.

### CODE REVIEW

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by jputrino** [comment]
There is a branch name in the conf.py file that has to be updated as the change is merged into the other branches.
```
rst_prolog = '''
.. raw:: html
   <script type="text/javascript">
    var home = "clouddocs.f5.com";
    var rtd = "f5-openstack-agent.readthedocs.io";
    if (window.location.hostname === rtd) {window.location.assign("http://" + home + "/products/openstack/agent/liberty);}
   </script>
'''
```

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by dflanigan** [comment]
test this please

**Comment by dflanigan** [comment]
test this please

**Comment by dflanigan** [comment]
test this please

**Comment by pjbreaux** [comment]
We turned off smoke on the liberty branch in the driver.

**Pull request merged**
