### PR TITLE
overcloud_vxlan is not a valid config

### PR DESCRIPTION
**Pull request by zancas**
@pjbreaux eliminate invalid Jenkins targets

### CODE REVIEW

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by zancas** [comment]
@pjbreaux what's the state here?

**Comment by pjbreaux** [comment]
@zancas: the reviewer hasn't reviewed it yet.

**Comment by zancas** [comment]
@szakeri what do you think?

**Pull request merged**
