### PR TITLE
Stable/newton

### PR DESCRIPTION
**Pull request by zancas**
@pjbreaux this PR contains the merge forward of mitaka I intended to put into #672 I _only_ included the fixes to `requirements.test.txt` in #672, here're the _rest_ of the changes. (As merged from mitaka.)

### CODE REVIEW

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by zancas** [comment]
Test this please.

**Comment by pjbreaux** [comment]
@zancas: it won't test for you until you are added to the admin list. I will do this once any and all kinks have been worked out.

**Comment by pjbreaux** [comment]
@zancas: please update your local stable/newton branch with the new changes from mitaka.

**Pull request merged**
