### PR TITLE
Add support for coverage aggregation and publication

### LINKED ISSUE #827: Collect agent coverage data from driver tests and publish to coveralls

### PR DESCRIPTION
**Pull request by zancas**
@pjbreaux 
#### What issues does this address?
Fixes #827

#### What's this change do?

If the driver Jenkins-driven tests run after the agent tests have run for a particular version (commit) of the agent this PR with aggregate and publish that coverage data.

### CODE REVIEW

**Comment by zancas** [comment]
In addition to the smoke tests please note the full build here:

http://10.190.25.149:49001/job/openstack/job/driver/job/mitaka/job/12.1.2-undercloud-vxlan/2/console

and the coverage results here:

https://coveralls.io/builds/13534001

**Comment by zancas** [comment]
@pjbreaux if we merge this then I think we'll have new coveralls data in the morning.

**Comment by pjbreaux** [comment]
@zancas: as we discussed, before we merge, please squash those commits that make sense to do so and fill out a commit template on the others.

**Comment by zancas** [comment]
@pjbreaux the jenkins master disk filled up.   I rebooted the executors.  When they came back online they didn't have the `/srv/nfs` mount point configured.   I marked them offline PR Jenkins is stalled until we can mount the correct `/srv/nfs` points and restart the executors.   I don't have access to your openstack tenant.

**Comment by pjbreaux** [comment]
retest this please

**Comment by pjbreaux** [comment]
@zancas: They're all back online. I added a script to make the mount points. I cleaned up the executors as well. A smoke test is running on this PR now.

**Comment by zancas** [comment]
@pjbreaux I've squashed.

**Pull request merged**
