### PR TITLE
Revert "F5 network mitaka issue 730 merge (#771)"

### PR DESCRIPTION
**Pull request by richbrowne**
This reverts commit b70c45218dc8631ddc6b5ab6fe5e9f7448a3091b.

@jgruber 
#### What issues does this address?
We have run into problems with the agent resiliency changes.  This commit reverts those changes so that they can run through an integration process.

### CODE REVIEW

**Comment by pjbreaux** [comment]
Can one of the admins verify this patch?

**Comment by pjbreaux** [comment]
If I run this test before the agent code has been reverted, the test will fail. But I'm going to kick it anyway.

**Comment by pjbreaux** [comment]
test this please

**Comment by richbrowne** [comment]
retest this please

**Pull request merged**
