### PR TITLE
Include concurrent patches to h3c-pike branch

### PR DESCRIPTION
**Pull request by zhaoqin-github**
@<reviewer_id>
#### What issues does this address?
Fixes #<issueid>
WIP #<issueid>
...

### CODE REVIEW

**Review by zongzw — COMMENTED** [review]
So, what's the behavior before this change?
In my understanding, the EntityManager and its children are instaniated for each request.

**Comment by zongzw** [comment]
The repo is set no-reviewer-requested?

**Comment by zhaoqin-github** [comment]
> So, what's the behavior before this change?
> In my understanding, the EntityManager and its children are instaniated for each request.

No. There is only one instance for every type of resource. For example, there is only one ListenerManager in memory, who is initiated when agent startup.

**Comment by zhaoqin-github** [comment]
> The repo is set no-reviewer-requested?

Maybe this branch is not correctly protected, but I do not have permission to modify it.

**Comment by olvandeng** [comment]
> > The repo is set no-reviewer-requested?
> 
> Maybe this branch is not correctly protected, but I do not have permission to modify it.

I added this branch protected as stable/pike.

**Review by Niklaus-xie — APPROVED** [review]
LGTM

**Comment by zhang-shengping** [comment]
LGTM

**Pull request merged**
