### PR TITLE
Fixes # 159 - address code review from @jgruber

### LINKED ISSUE #159: Fix documentation bugs/inaccuracies
#### OpenStack Release
Liberty +

#### Description
I asked @jgruber to review the docs and give me feedback. Now I need to fix all the issues he identified in his email.

### PR DESCRIPTION
**Pull request by jputrino**
@jgruber @mattgreene @jlongstaf 
#### What issues does this address?
Fixes #159 

#### What's this change do?
Fixes bugs in documentation.

#### Where should the reviewer start?
View the staged docs at http://lbaasv2-test.readthedocs.io/en/feature.docs-bugfix/index.html. 

#### Any background context?

- change references to 'active-standby' and 'active-active' to match how they're used in f5 documentation (using dash, not slash)
- copy diagrams over from lbaasv1
- fix undercloud diagram per code review from @jgruber
- replace one-arm and multiple-arm mode diagrams
- add ha active-standby pair diagram to ha mode doc
- edit l2 adjacent mode figure
- add diagram of scalen cluster to clustering doc

### CODE REVIEW

**Comment by jputrino** [comment]
FYI @jlongstaf & @jgruber -- I included you here because I'd like your eyes on/feedback; I actually assigned the PR to @mattgreene, so he's ultimately responsible for merging it in. Thanks to all in advance!

**Comment by mattgreene** [comment]
I might have lost an email.  Are you still working on this PR?  It has a merge conflict to resolve before we accept the request.

**Comment by jputrino** [comment]
Looks like I have to fetch and rebase. Working on that now.

**Comment by jputrino** [comment]
All set! I believe @jgruber was also going to review these changes, since he requested them.

**Comment by mattgreene** [comment]
Ok.  Let's wait until Monday, then be ready to merge the PR in order to prime for Mitaka.

**Comment by jputrino** [comment]
Sounds good!

-- Jodie Putrino

On Jul 8, 2016, at 3:44 PM, Matt Greene <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok. Let's wait until Monday, then be ready to merge the PR in order to prime for Mitaka.

-

**Pull request merged**
